AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    lex-dynamodb

    Example of how a serverless app can handle Lex requests and log intent and/or session data to dynamodb.
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10

Parameters:
  TableName:
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers or special characters allowed.
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MaxLength: 50
    Default: LexActivity
    MinLength: 3
    Type: String

Resources:
  LogIntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: log-intent
      Description: Log Lex intent to a DynamoDB table
      CodeUri: log-intent/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - Statement:
          - Action:
            - cloudwatch:PutMetricData
            Resource: '*'
            Effect: Allow
        - Statement:
          - Action:
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
            Resource:
              Fn::Sub:
              - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
              - tableName:
                Ref: TableName
            Effect: Allow
          MemorySize: 128
          Environment:
              Variables:
                  TABLE_NAME:
                      Ref: TableName
                  PRIMARY_KEY:
                      Fn::Sub: ${TableName}Id
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
        KeySchema:
        - KeyType: HASH
        AttributeName:
            Fn::Sub: ${TableName}Id
        TableName:
            Ref: TableName
        AttributeDefinitions:
        - AttributeName:
            Fn::Sub: ${TableName}Id
            AttributeType: S
        ProvisionedThroughput:
            WriteCapacityUnits: 1
            ReadCapacityUnits: 1

Outputs:
    log-intent:
      Description: "Lambda function that takes Lex fulfillment requests and logs them to DynamoDB"
      Value: 
        Fn::GetAtt:
        - log-intent.Arn

    DynamoDBTableArn:
    Description: The ARN of your DynamoDB Table
    Value:
      Fn::GetAtt:
      - DynamoDBTable
      - Arn
